name: taquin
description: "Taquin game"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3 # Mettre à jour la version de flutter_launcher_icons
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png" # Assurez-vous que le chemin est correct

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png # Ajoutez l'image dans la section assets