name: taquin
description: "Taquin game"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  image_picker: ^1.1.2
  flutter_plugin_android_lifecycle: ^2.0.22
  file_picker: ^8.3.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png

